### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by yaslim** [stephenmcd/django-socketio#103]
Hello, 

I have a error and I don't know why it's appears only when I tried to send a **message with accents** (and specials characters ?)

I have this error : 

```
127.0.0.1 - - [2016-07-10 16:45:33] "POST /projets/Second%20projet%20of%20me/commentaires HTTP/1.1" 200 261 0.212520
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 49, in handle
    handler.handle()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 180, in handle
    result = self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 314, in handle_one_request
    self.handle_one_response()
  File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 68, in handle_one_response
    jobs = self.transport.connect(session, request_method)
  File "/usr/local/lib/python2.7/dist-packages/socketio/transports.py", line 101, in connect
    return self.handle_post_response(session)
  File "/usr/local/lib/python2.7/dist-packages/socketio/transports.py", line 67, in handle_post_response
    messages = self.decode(data)
  File "/usr/local/lib/python2.7/dist-packages/socketio/transports.py", line 16, in decode
    return self.handler.environ['socketio'].decode(data)
  File "/usr/local/lib/python2.7/dist-packages/socketio/protocol.py", line 113, in decode
    messages.append(json.loads(data[3:size]))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
<Greenlet at 0x7fec3e5c52d0: <bound method SocketIOServer.handle of <SocketIOServer at 0x7fec3e721710 fileno=3 address=127.0.0.1:8000>>(<socket at 0x7fec3e2f2ad0 fileno=[Errno 9] Bad fil, ('127.0.0.1', 50395))> failed with ValueError
```

**Comment by stephenmcd** [comment]
What was the solution?
