### ISSUE TITLE
why i use """runserver_socketio 0.0.0.0:9443"""  the django web is running? 

### ISSUE THREAD

**Issue by Rambo-rambo** [stephenmcd/django-socketio#109]
/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/bin/python2.7 /data/RAMBO/vsec_code/vSecCenter3.2.0/restapi/manage.py runserver_socketio 0.0.0.0:9443

SocketIOServer running on 0.0.0.0:9443

Traceback (most recent call last):
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/socketio/server.py", line 49, in handle
    handler.handle()
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/gevent/pywsgi.py", line 443, in handle
    result = self.handle_one_request()
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/gevent/pywsgi.py", line 658, in handle_one_request
    self.handle_one_response()
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/socketio/handler.py", line 68, in handle_one_response
    jobs = self.transport.connect(session, request_method)
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/socketio/transports.py", line 92, in connect
    self.write_packed(session_id)
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/socketio/transports.py", line 19, in write_packed
    self.write(data)
  File "/data/RAMBO/vsec_code/vSecCenter3.2.0/bin/python2.7/lib/python2.7/site-packages/socketio/transports.py", line 22, in write
    if 'Content-Length' not in self.handler.response_headers_list:
AttributeError: 'SocketIOHandler' object has no attribute 'response_headers_list'
<Greenlet at 0x3091190: _handle_and_close_when_done(<bound method SocketIOServer.handle of <SocketIOSe, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x305f750 fileno=[Errno 9] Bad file de)> failed with AttributeError

**Comment by Rambo-rambo** [comment]
is this because i am running this inside a virtualenv?   but "sudo python" is use the systerm‘s python

**Comment by stephenmcd** [comment]
#63

**Comment by Rambo-rambo** [comment]
thanks, it really fix my problem
