### ISSUE TITLE
Updating django-socketio to use the latest socketio client (0.8.5)

### ISSUE THREAD

**Issue by tabouassaleh** [stephenmcd/django-socketio#19]
I am working on a web app using django and socket.io, and have been trying to use django-socketio to connect the two. I noticed that the the socketio client packaged with the app was using xhr-multipart and xhr-polling on the latest FireFox (10.0.2) and Chrome (17.0.963.56), respectively. I tried replacing the client library with the [latest version](https://github.com/LearnBoost/socket.io-client) (0.8.5) but now I get an error on the server side:

```
 Traceback (most recent call last):
  File "/home/taa/env/lib/python2.6/site-packages/gevent/pywsgi.py", line 438, in handle_one_response
    self.run_application()
  File "/home/taa/env/lib/python2.6/site-packages/gevent/pywsgi.py", line 425, in run_application
    self.process_result()
  File "/home/taa/env/lib/python2.6/site-packages/gevent/pywsgi.py", line 416, in process_result
    self.write(data)
  File "/home/taa/env/lib/python2.6/site-packages/gevent/pywsgi.py", line 373, in write
    self.socket.sendall(msg)
  File "/home/taa/env/lib/python2.6/site-packages/gevent/socket.py", line 504, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/home/taa/env/lib/python2.6/site-packages/gevent/socket.py", line 490, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
<SocketIOServer fileno=3 address=0.0.0.0:8182>: Failed to handle request:
  request = GET /socket.io/1/?t=1330535867416 HTTP/1.1 from ('216.16.232.86', 1154)
  application = <django.contrib.staticfiles.handlers.StaticFilesHandler object at 0x2d0b950>

x.x.x.x - - [2012-02-29 11:17:52] "GET /socket.io/1/?t=1330535867416 HTTP/1.1" 500 0 0.384851
```

Any idea what the issue may be? And any plans to upgrade the socketio client library packaged with the app or make the app compatible or socketio-client v0.8.5?

I don't know much about the WebSocket protocol, but I'm willing to help however I can, such as testing different browsers and what not.

**Comment by thetylerhayes** [comment]
Is work on this still underway? Socket.io is up to 1.3.5 now :cake:

**Comment by krishn2014** [comment]
Hi, Is this lib still under development. Let me know I will also like to contribute if their is some blockers.. The current socket.io is 1.3.5

**Comment by PoopFeast6969** [comment]
I'd also like to know if this is still being maintained, since I couldn't get the server to receive any information from the client socket.io. Tried all the recommended dependency versions that where suggested in other issues.

**Comment by papaloizouc** [comment]
using the example_project and:
```
gevent-socketio==0.3.6
gevent-websocket==0.9.3
```
```
socket = SocketIOChannelProxy(request.environ["socketio"])
KeyError: 'socketio'
```

**Comment by stephenmcd** [comment]
For anyone asking what's happening with this thread, if it's still open and nothing has been mentioned, that means the work hasn't been done!

I just deleted a handful of "is anything happening here?" messages, since they're just noise.

**Comment by papaloizouc** [comment]
For information.
I have pending work, the gevent-socketio package changed a lot and i think may features implemented in this package have been moved inside gevent-socketio.
I have enough work done but i mostly rely on source code and blogs to fix it. I may be able to finish it my my work so far is draft. If anyone feels like picking up from what i've left on my branch so far feel free, It might take me some time because i have something else to finish too.

https://github.com/papaloizouc/django-socketio/tree/support_for_0_3_6
http://www.pixeldonor.com/2014/jan/10/django-gevent-and-socketio/

**Comment by stephenmcd** [comment]
Thanks @papaloizouc that looks really useful!

**Comment by SparksFyz** [comment]
Hi,  @stephenmcd   when I played with the chat demo, I find the transports of django-socketio is xhr-polling,  the request is just like this
` http://localhost:9000/socket.io/xhr-polling/13232844055/1452756180603` ,  how can I use websocket?
