### ISSUE TITLE
Issues with Django 1.8.2 and fresh install

### ISSUE THREAD

**Issue by zocario** [stephenmcd/django-socketio#79]
Hi, I am having issues using django-socketio with a fresh project using Django 1.8.2 and python 2.7.6.
When I try to establish a socket connection I got an handshake error client side:

![capture d ecran 2015-06-03 a 15 22 01](https://cloud.githubusercontent.com/assets/800617/7960929/5c6203da-0a04-11e5-8ecc-048413d5c0af.png)

And server side I have this output:

    Traceback (most recent call last):
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/socketio/server.py", line 49, in handle
        handler.handle()
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/gevent/pywsgi.py", line 184, in handle
        result = self.handle_one_request()
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/gevent/pywsgi.py", line 321, in handle_one_request
        self.handle_one_response()
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/socketio/handler.py", line 68, in handle_one_response
        jobs = self.transport.connect(session, request_method)
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/socketio/transports.py", line 92, in connect
        self.write_packed(session_id)
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/socketio/transports.py", line 19, in write_packed
        self.write(data)
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/socketio/transports.py", line 22, in write
        if 'Content-Length' not in self.handler.response_headers_list:
    AttributeError: 'SocketIOHandler' object has no attribute 'response_headers_list'
    <Greenlet at 0x10c9c22d0: <bound method SocketIOServer.handle of <SocketIOServer at 0x10ce7b690 fileno=5 address=127.0.0.1:9000>>(<socket at 0x10d32b150 fileno=[Errno 9] Bad file d, ('127.0.0.1', 51914))> failed with AttributeError

    /Users/zocario/wicrian/lib/python2.7/site-packages/django_socketio/urls.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
      from django.utils.importlib import import_module

    127.0.0.1 - - [2015-06-03 13:13:15] "GET /my_space/videos/ HTTP/1.1" 200 5267 0.105770
    127.0.0.1 - - [2015-06-03 13:13:15] "GET /static/WicrianApp/css/base.css HTTP/1.1" 304 66 0.001442
    127.0.0.1 - - [2015-06-03 13:13:15] "GET /static/WicrianApp/images/logo.png HTTP/1.1" 304 66 0.000508
    127.0.0.1 - - [2015-06-03 13:13:15] "GET /static/js/socket.io.js HTTP/1.1" 304 66 0.000419
    Traceback (most recent call last):
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
        result = self._run(*self.args, **self.kwargs)
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/socketio/server.py", line 49, in handle
        handler.handle()
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/gevent/pywsgi.py", line 184, in handle
        result = self.handle_one_request()
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/gevent/pywsgi.py", line 321, in handle_one_request
        self.handle_one_response()
      File "/Users/zocario/wicrian/lib/python2.7/site-packages/socketio/handler.py", line 58, in handle_one_response
        self.handle_one_response(call_wsgi_app=False)
    TypeError: handle_one_response() got an unexpected keyword argument 'call_wsgi_app'
    <Greenlet at 0x10dce1e10: <bound method SocketIOServer.handle of <SocketIOServer at 0x10ce7b690 fileno=5 address=127.0.0.1:9000>>(<socket at 0x10dcddd50 fileno=[Errno 9] Bad file d, ('127.0.0.1', 51925))> failed with TypeError

Here is my ```pip freeze``` output:

    amqp==1.4.6
    anyjson==0.3.3
    billiard==3.3.0.20
    boto==2.38.0
    celery==3.1.18
    cffi==1.0.0
    cryptography==0.9
    Django==1.8.2
    django-enumfields==0.7.3
    django-socketio==0.3.9
    django-widget-tweaks==1.3
    enum34==1.0.4
    gevent==1.0.2
    gevent-socketio==0.2.1
    gevent-websocket==0.9.5
    google-api-python-client==1.4.0
    greenlet==0.4.7
    httplib2==0.9.1
    idna==2.0
    ipaddress==1.0.7
    kombu==3.0.26
    librabbitmq==1.6.1
    oauth2client==1.4.10
    pyasn1==0.1.7
    pyasn1-modules==0.0.5
    pycparser==2.13
    pyOpenSSL==0.15.1
    pytz==2015.4
    rsa==3.1.4
    simplejson==3.7.1
    six==1.9.0
    sphinx-me==0.3
    uritemplate==0.6

Is Django 1.8.2 supported? Or is there something else in my config that is wrong?
Thanks!

**Comment by mmmaaaxxx77** [comment]
I get the problem, too. I run the example project, creating a chat room is fine, but when I open the room page, console shows "../../django_socketio/urls.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module".
It looks like this version does not support Django 1.8+.

**Comment by MikeSoft** [comment]
I have this issue too =/

**Comment by Benoit-Besnier** [comment]
You should clone install the binary available on git instead of using package manager. You can also follow this to solve your issues by your self.
[http://stackoverflow.com/questions/32761566/django-1-9-importerror-for-import-module/32761567#32761567](url)

**Comment by stephenmcd** [comment]
Merging with #106
