### ISSUE TITLE
error: [Errno 32] Broken pipe?

### ISSUE THREAD

**Issue by LiangAllen** [stephenmcd/django-socketio#86]
[2015-11-30 11:54:19] "GET /socket.io/websocket HTTP/1.1" socket - 0.291006
Traceback (most recent call last):
  File "/application/python/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/application/python/lib/python2.7/site-packages/gevent/pywsgi.py", line 495, in run_application
    self.process_result()
  File "/application/python/lib/python2.7/site-packages/gevent/pywsgi.py", line 486, in process_result
    self.write(data)
  File "/application/python/lib/python2.7/site-packages/gevent/pywsgi.py", line 380, in write
    self._write_with_headers(data)
  File "/application/python/lib/python2.7/site-packages/gevent/pywsgi.py", line 400, in _write_with_headers
    self._sendall(towrite)
  File "/application/python/lib/python2.7/site-packages/gevent/pywsgi.py", line 355, in _sendall
    self.socket.sendall(data)
  File "/application/python/lib/python2.7/site-packages/gevent/socket.py", line 460, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/application/python/lib/python2.7/site-packages/gevent/socket.py", line 437, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
{u'CSRF_COOKIE': u'ma28Z8BPTrIni3bcfPzD5fnx0EI9LwuP',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.8',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Upgrade',
 'HTTP_COOKIE': 'sessionid=hluk3o77xlt33mlpru352lxf8dis3bn3; csrftoken=ma28Z8BPTrIni3bcfPzD5fnx0EI9LwuP',
 'HTTP_HOST': '192.168.0.223:8001',
 'HTTP_ORIGIN': 'http://192.168.0.223:8000',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_SEC_WEBSOCKET_EXTENSIONS': 'permessage-deflate; client_max_window_bits',
 'HTTP_SEC_WEBSOCKET_KEY': 'Zga9rfD5SVlyfz06AiibOA==',
 'HTTP_SEC_WEBSOCKET_VERSION': '13',
 'HTTP_UPGRADE': 'websocket',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
 'PATH_INFO': u'/socket.io/websocket',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.0.64',
 'REMOTE_PORT': '6510',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': '192.168.0.223',
 'SERVER_PORT': '8001',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f0f996ac1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7f0f8d092b90>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with error

version 
django 1.8.3
django-socketio 0.39
gevent 1.0.2
greenlet 0.49
gevent-socketio 0.3.6
sphinx-me 0.3

**Comment by bodieskate** [comment]
A very similar error was noted in [this Flask-Socket.io](https://github.com/miguelgrinberg/Flask-SocketIO/issues/33) project. You might want to try downgrading gevent to, I believe, 0.9.16.

There appears to be a lack of support for specific wsgi servers in gevent >= 1.0
